### PR TITLE
Anti-replay (RFC4303 Appendix A)

### PR DESCRIPTION
**Pull request by vanfstd**
This implements and adds tests for IPsec anti-replay as per RFC4303 Appendix A, except for the resynchronization (App. A3) which will get its own PR.
Note that the test cases produce "auditable events" which end up on stdout.

Feedback appreciated.

### CODE REVIEW

**Comment by vanfstd** [comment]
Ugh, stand by.

**Comment by eugeneia** [comment]
I have merged `master` into `ipsec`and pushed it, would GitHub to update the PR soon(?).

**Comment by eugeneia** [comment]
Hmm GitHUb doesn't seem to pick up the updated branches, maybe close/reopen? Not sure if that will do anything.

**Comment by vanfstd** [comment]
I'll recreate the pull request from a different branch

**Pull request closed without merging**
