### PR TITLE
Initial import of intel_avf driver

### PR DESCRIPTION
**Pull request by petebristow**

### CODE REVIEW

**Comment by eugeneia** [comment]
Oooh neat!!

**Comment by lukego** [comment]
So this is ~700 LOC to support all Intel NICs present and future? That would be nice!

**Comment by lukego** [comment]
(I am really looking forward to reading this code properly once I have the next Studio release out the door...)

**Comment by petebristow** [comment]
There are some tests, fixes and cleanup pending.

**Comment by eugeneia** [comment]
Minor markdown formatting nitpick: markdown needs newlines between `— **thing** *args*` and the following paragraph to render the item “properly”. Also there seems to be some markdown parsing issue in the npackets diagram.

See: https://github.com/snabbco/snabb/blob/e50404a2fd81e3d582e24209a733f120e2caab7f/src/apps/test/README.md#npackets-appstestnpackets

**Pull request merged**
