### PR TITLE
intel_mp: Poll more frequently for linkup

### PR DESCRIPTION
**Pull request by wingo**
This patch lowers the link-up poll period from 2 seconds to 0.1
second, for faster reactions on link state change.  It also makes the
82599 linkup wait loop just wait on link state change, like the old
Intel82599 driver, instead of also doing reset logic in the wait loop.

### CODE REVIEW

**Comment by wingo** [comment]
I wonder if the linkup poll period should be configurable though -- seems like a useless configuration option, one that we should just set appropriately.  I could make it a file-local variable instead.  WDYT @petebristow ?

**Comment by petebristow** [comment]
The reset logic is in the loop because the card can wedge trying to come up. Particularly if the port is already seeing significant traffic during the reset. If you have it hooked up to a switch span port for instance. I wasn't able to come up with a test that would reliably fail if this code wasn't in place but if I ran selftest 1000 times I would get a few failures that went away with repeated resetting of the card. It's possible this is more an indication on the cheap cards / SFP+ DACs I'm using. 2 seconds appeared to be the sweet spot if it didn't come up after that period of time then it wasn't going to.

**Comment by wingo** [comment]
This PR fixes #1141 fwiw.  I would say that 2s polling is not a good default and is specifically a regression relative to Intel82599 where it wasn't necessary.  Something needs to be done though, wdyt is the right way forward @petebristow ?

**Comment by petebristow** [comment]
I don't follow, https://github.com/snabbco/snabb/blob/master/src/apps/intel/intel10g.lua#L126-L154 shows the Intel82599 doing a very similar thing of waiting on a link up and bouncing the card if it's not seen within a period of time. The control flow is a little more convoluted but the gist is the same. Are you objecting to the "something went wrong bounce the card until it works" methodology or that 2 seconds is too long to wait for the majority of cases where the card comes up ok first time?

**Comment by wingo** [comment]
Hi, I see what you are saying, I didn't notice that bit before.  I have no objection to the loop actually, but I want a more reactive response to link-up.  You can see here that the older driver polls more frequently between resets: https://github.com/snabbco/snabb/blob/master/src/apps/intel/intel10g.lua#L394.

**Comment by wingo** [comment]
I'll update the patch appropriately.

**Comment by wingo** [comment]
Updated to re-introduce reset loop for 82599 cards and factor out the linkup wait loop.

**Comment by wingo** [comment]
wdyt @petebristow ?

**Comment by wingo** [comment]
The previous build failure was actually a bot failure I think.  Merged master to this branch and we'll see what the results are now.  @petebristow review still welcome, though @takikawa perhaps you would be available to review as well?

**Comment by teknico** [comment]
LGTM. 0.1 seconds seems a good middle ground between the old driver behavior and 2 seconds.

**Pull request closed without merging**
