### PR TITLE
Merge max-next into next (for v2018.01.1 bugfix release?)

### PR DESCRIPTION
**Pull request by eugeneia**
* [x] Merge #1280 
* [x] Merge #1277 
    - [x] Make sure that fix is valid
* [x] Merge #1273
* [x] Merge  #1283
* [x] Verify this passes the CI

### CODE REVIEW

**Comment by eugeneia** [comment]
There are some [lwaftr test failures](https://gist.github.com/SnabbBot/d5d169ab3c3f382334ec70aae8e59c98#file-log-L2898) that appear to be ralted to the new `lib.ptree`. Is that something you recognize @wingo ?

**Comment by dpino** [comment]
@eugeneia I think this patch fixes the issue: https://github.com/Igalia/snabb/commit/ea5228c6d9de864480381ea91c9a26fc01e6df1f I can make a PR to snabb upstream

**Comment by dpino** [comment]
@eugeneia PR to next https://github.com/snabbco/snabb/pull/1282

**Comment by eugeneia** [comment]
@dpino that does not seem to fix it.

**Comment by dpino** [comment]
@eugeneia OK, sorry it didn't fix the issue completely. But I'm sure that patch it's necessary. I pulled out max-next and I'm running it in our machines. lwAFTR's selftest don't pass yet. I give you a shout when I fix it.

**Comment by dpino** [comment]
I found out the issue. lwAFTR's loadtest was failing due to a non existing parameter "pci-address". To fix it i'ts necessary to apply this patch https://github.com/Igalia/snabb/pull/1005/commits/3e7d2b5e1864959186c393ea65f2e9f3a364a7d3

**Comment by dpino** [comment]
PR: https://github.com/snabbco/snabb/pull/1283

**Comment by eugeneia** [comment]
👍 🎆  Looks good to me! Cc @lukego

**Comment by eugeneia** [comment]
Superseded by  #1285 (go via the `fixes` branch)

**Pull request closed without merging**
