### PR TITLE
Add Nix expressions to build Snabb

### PR DESCRIPTION
**Pull request by domenkozar**
Hydra is currently using these in [release.nix](https://gist.github.com/83aebe9b7f4b443685ab38405b2b356d.git) and they build successfully at https://hydra.snabb.co/jobset/snabb/master

It's a good idea to put the upstream, because different Snabb versions may need different the Nix expressions. It's also handy to clone Snabb and just run `nix-build release.nix` and you should get the snabb, manual and tests (with logs) for that particular commit (if tests didn't fail).

There are two blockers:

- I have no way to extract Snabb version from the repo. Running a command won't help in Nix. It needs to be statically in a file. Currently no version is added to the derivation name.
- We depend on `git` for manual and also Snabb at build time. This is problematic since hash in Nix is content addressed (`src = ./.;` and `.git` mutates on each commit and thus changes regardless of the commit checkout. See my upstream comment at https://github.com/NixOS/nixpkgs/issues/8567#issuecomment-211362769

PS: There are lots of commits, maybe kbara-next needs to be rebase on master? Or should I just rebase on kbara-next?

### CODE REVIEW

**Comment by domenkozar** [comment]
It won't let me force push since it's a protected branch, so can't rebase on top of `kbara-next`. Sorry for the mess :-) cc @lukego @eugeneia

**Comment by kbara** [comment]
@lukego is there anything it'd be helpful for me to do with kbara-next, like merge master into it? I'm still getting used to the upstream Snabb workflow... :-)

**Comment by lukego** [comment]
Hey, cool, there is actually no mess here and everybody is doing the right thing :) we are exercising a new edge in our collaboration graph here :-).

The reason we see many commits here is that downstream branch `nix` has merged a bunch of commits from the `v2016.04` release on `master` but these commits are not yet in `kbara-next`. So Github is neatly showing that the consequence of merging `nix` onto `kbara-next` would be to get all of these commits i.e. the `v2016.04` release in addition to Domen's own change a357165.

The next steps could be either of these things:

1. `kbara-next` merges from `master` and then this PR should automatically update to show only the commits that are still missing i.e. a357165. Then this could be merged.
2. `kbara-next` merges from `nix` which in one fell swoop would bring in the `v2016.04` release and also Domen's change.

So @kbara it is really up to you which you prefer.

In a perfect world we might all merge `master` into our long-lived branches immediately when a new release is made, but this demand-driven merge may well be fine too. The main thing is to transfer all the commits between all the branches and git is good at keeping track of what is missing.

**Comment by lukego** [comment]
Here is one git incantation to summarize the changes more succinctly:

```
$ git log --oneline --first-parent origin/kbara-next..origin/nix
a357165 Add Nix expressions to build Snabb project
03f5958 Merge PR #855 (v2016.04 release) onto master
```

**Comment by kbara** [comment]
Excellent. I've run git merge upstream/master on kbara-next and pushed that; I agree that doing that after each release sounds like a good workflow.

**Comment by lukego** [comment]
@kbara You will need to push your branch directly to the `snabbco` repo now e.g. with `git push snabbco kbara-next` if you have a remote called `snabbco`. The mirroring-from-our-forks hack is gone now - see #850.

**Comment by kbara** [comment]
Interesting. I've done that, it looks to me like it's updated, but the list of commits/etc above doesn't update.

**Comment by lukego** [comment]
Interesting, yep. I see that you have pushed:

```
$ git log -1 --oneline origin/kbara-next
d5d355a Merge remote-tracking branch 'upstream/master' into kbara-next
$ git log --oneline origin/kbara-next..origin/nix
a357165 Add Nix expressions to build Snabb project
```

but I suppose that the Github UI does not automagically refresh in this case. Oh well, probably not a big deal.

**Comment by kbara** [comment]
Yeah; I couldn't find a way to manually do that either. All the more reason to do this right after releases, eh?

**Comment by kbara** [comment]
There is a trailing whitespace after ```+      tar xvzf ${test_env} -C ~/.test_env/ ```; is this something people care about on this project?

**Comment by kbara** [comment]
```
+      export SNABB_PCI0="0000:01:00.0"
+      export SNABB_PCI_INTEL1="0000:01:00.1"
+      export SNABB_PCI_INTEL0="0000:01:00.0"
```
will clearly only work on some machines. Is the intent for this to just be running on the snabblab servers? If not, how are people with other PCI IDs expected to use it - local modifications to this file?

**Comment by kbara** [comment]
Aside from those two nits, it looks good to me, with the caveat that I haven't dug deeply into nix yet. :-)

**Comment by domenkozar** [comment]
You're right. I'll make sure the `SNABB_PCI* exports can be superseeded via bash env. And that whitespace should be gone.

**Comment by domenkozar** [comment]
Pushed the two fixes, but the diff is bigger now:

```
$ git log --oneline origin/kbara-next..origin/nix
6cce8f4 release.nix: whitespace
8982625 release.nix: respect bash env, provide fallback values
e1ff0a3 Swapped in lstopo.png, replacing lstopo.pdf
aa1aac9 Renamed performance tuning file, as per review request
afc0bfb added info on mlock=on
294fc3b braindump on performance parameters
dbe9a9a Initial stub on performance tuning
a357165 Add Nix expressions to build Snabb project
```

**Comment by domenkozar** [comment]
I've removed WIP, the two issues I mentioned can be addressed later.

**Pull request merged**
