### PR TITLE
pci_bind: A utility to bind/unbind PCI cards

### PR DESCRIPTION
**Pull request by kbara**
Everyone seems to have their own shell scripts to bind/unbind PCI cards. This patch adds a tool to consolidate the key options into Snabb. It's more Snabb-like to not need to have Snabb *and* an external shell script to use Snabb.

```
  pci_bind [-ubir] <PCI-ADDRESS>
  pci_bind [-ah]

  -a, --all
                             Restore all PCI addresses to kernel management
  -b, --bind <PCI-ADDRESS>
                             Bind the PCI address to the kernel
  -h, --help
                             Print usage information
  -i, --info <PCI-ADDRESS>
                             Print out the associated Linux interface name
  -r, --remove <PCI-ADDRESS>
                             Remove the specified PCI address
  -u, --unbind <PCI-ADDRESS>
                             Unbind the PCI address, so Snabb can use it

```

See the README for more details.

### CODE REVIEW

**Comment by kbara** [comment]
@eugeneia , are you happy to be the upstream on this?

**Comment by eugeneia** [comment]
@kbara Sure! This is super handy, I will merge this as-is.

**Comment by kbara** [comment]
Thank you :)

**Comment by mwiget** [comment]
@kbara: super useful! Thanks and yes, I also have my bag of shell scripts for this task, which I'll happily retire ;-)

**Comment by kbara** [comment]
@mwiget shout if it lacks any features you need. :-)

**Comment by lukego** [comment]
Really nice :).

**Pull request merged**
