### PR TITLE
Merge `lwaftr` to next

### PR DESCRIPTION
**Pull request by wingo**
This PR mainly includes fixes to `snabbvmx`, getting it to the point where it works reliably under Hydra.  Thanks very much to @dpino, @teknico, and @domenkozar for this work..  It also includes #1033 from @xray7224.

### CODE REVIEW

**Comment by wingo** [comment]
I think this PR is pretty low-risk; the only tricky change is the "named programs" one.  For me it could hit master for v2016.11, or we could wait until v2016.12, either way.  WDYT @eugeneia and @lukego ?

**Comment by domenkozar** [comment]
`ERROR     testlog/program.snabbvmx.tests.selftest.sh`

**Comment by lukego** [comment]
Let's wait for v2016.12. I have already advertised `next` as ready for v2016.11 release in https://github.com/snabbco/snabb/pull/1060#issuecomment-258388939 so I prefer to only merge fixes to release-blockers at the moment.

**Comment by wingo** [comment]
Makes sense to me.  I didn't realize that non-core code could be risky but it turns out it can be if the test suites are flaky or don't run on the main CI servers.

**Comment by wingo** [comment]
Closing this PR, as it keeps getting new commits as we merge to `lwaftr`.  I'll instead merge via `wingo-next`.

**Pull request closed without merging**
