### PR TITLE
Add minimal CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by eugeneia**
Adds a `CONTRIBUTING.md` file as discussed in #761. What did I miss, what should I edit out?

Cc @lukego @kbara @wingo

### CODE REVIEW

**Comment by kbara** [comment]
LGTM. There should probably be a way for people submitting PRs to figure out who the maintainers are, perhaps a maintainers.md or similar.

**Comment by lukego** [comment]
Short and sweet!

I would like to tweak the COPYRIGHT section so that we are not encouraging people to register their copyrights but merely telling them how they can do so. For example:

> If you want to record a copyright notice with your contribution then you can optionally do this in the file src/COPYRIGHT. (Copyright notices inside source files will be rejected or removed because that is not our style.)

**Comment by wingo** [comment]
LGTM as well.  (I still am not clear about who is the "upstream" for patches written by @eugeneia, @kbara, or me; I guess in this case with a positive review we should feel free to land them on our own branches?)

**Comment by kbara** [comment]
I've been wondering that as well, though guessing the opposite - that our patches would land on the branches of another maintainer. Both options have quirks. :-)

**Comment by lukego** [comment]
Long term the goal is to bootstrap us into the Linux model where every change has an unambiguous upstream branch based on its subject matter (documentation vs intel drivers vs virtio drivers, etc). The actions we take should be leading us in that direction. But how? :-)

More immediately: if maintainers are getting frustrated that nobody merges their patches then it may be a general process issue with assigning upstreams. In that case it could be counter-productive to create an exception mechanism that only works for maintainers since everybody else will be stuck.

Should we experiment with a different way of assigning upstreams? I would be willing to do this manually based on my own perception of who should review a change and how much they are backlogged if we want to try that.

**Comment by lukego** [comment]
(Or maybe the process today works once we declare that PRs to master should be assigned an upstream to merge them, even when submitted by maintainers.)

**Comment by lukego** [comment]
... blathering a bit ...

Could also define a tag `needs-upstream` that any of us can apply simply to flag when a change risks being reviewed with no clear path forward e.g. immediately after a PR is opened. (This state is perhaps implicit by looking for PRs that are not marked `[sketch]` and have no upstream but maybe explicit is better than implicit, I dunno.)

**Comment by eugeneia** [comment]
> I would like to tweak the COPYRIGHT section so that we are not encouraging people to register their copyrights but merely telling them how they can do so

Good point. Done.

Regarding the question who is upstream for my PRs: I thought it would be either @wingo or @kbara depending on whoever self-assigns. Before we implement a complicated “who-is-upstream” I will propose to rephrase the question to “why should I *not* be upstream?” (e.g. “because I am the PR author”, ”because I don't have time”, “because I know somebody else who should be upstream”, ...). When there is no clear answer to that question we self-assign. If the decision was “wrong” it can be contested at any time.

**Comment by kbara** [comment]
I like that set of heuristics.

**Comment by kbara** [comment]
This looks fine to me. @eugeneia , do you consider it merge-ready?

**Comment by eugeneia** [comment]
@kbara Yes, I am sure we will edit it later on based on feedback from when its prominent but for now I think its a good initial version.

**Comment by kbara** [comment]
Agreed. Merged, thank you.

**Pull request merged**
