### PR TITLE
Modify OpenStack table parsing to comply with Liberty release

### PR DESCRIPTION
**Pull request by domenkozar**
'driver' column is now gone, so we rely on `vif_type` to detect if snabb is configured.

Since port_bindings table changes, this is a backwards incompatible
change with previous OpenStack releases.

### CODE REVIEW

**Comment by eugeneia** [comment]
@domenkozar Sorry, overlooked this for quite a while. Can you update the [selftests](https://gist.github.com/SnabbBot/2953e28abc09bfdbb8cb#file-log-L303) to pass?

**Comment by domenkozar** [comment]
@eugeneia done. It's taking a long time for snabbbot to report back, but locally it looks good.

**Comment by domenkozar** [comment]
@eugeneia Silly mistake - pushed the wrong repo. This is ready for review. cc @lukego

**Comment by eugeneia** [comment]
Related: #661

**Pull request merged**
