### PR TITLE
Add VMDq support to intel_mp driver

### PR DESCRIPTION
**Pull request by takikawa**
This PR is for work-in-progress improvements for the intel_mp driver we have been working on at Igalia. The goal of this work is to start adding support for VMDq mode for intel_mp to bring it closer to feature parity with the intel10g driver.

Specifically, this PR code supports VMDq mode with RSS (32 VM pools with 4 RSS queues each) with MAC/VLAN filtering on the Intel 82599. Some of the code is ported from the intel10g driver. For now, the driver just rejects VMDq mode on i210 and i350 NICs.

This work is still on-going and we are planning additional work to port more features supported in intel10g to the intel_mp driver, so that the intel_mp driver can potentially replace the intel10g driver.

We are submitting a PR now so that we can get some early feedback on the work, and to avoid submitting a huge set of commits at the end for review. We also want to make sure that the tests still pass on i210 and i350 NICs, since we don't currently have any available for development.

If the changes look ok, we would be happy to merge this incrementally and submit PRs for additional work.

We'd definitely appreciate any feedback about the design approach or the implementation. (CC @petebristow and @lukego)

### CODE REVIEW

**Comment by takikawa** [comment]
Hello folks. We updated this branch with more recent development work on `intel_mp`. At this point, the `intel_mp` driver code in this PR is compatible enough with `intel10g` that we can switch over all the snabb programs to use it and CI will pass. We put the code required to switch over to `intel_mp` on a separate branch to keep this PR smaller and less invasive.

The PR also fixes a few performance issues and we are working on doing more extensive performance testing.

Any feedback would be very helpful, especially on user-facing aspects like the configuration of the VMDq pools or the general approach to integrating these features. Apologies for the large code dump, but we figured it would be more useful to have the entire driver code instead of the initial PR that we had.

**Comment by lukego** [comment]
This is amazing work!

I need to wrestle a little more with my trace visualization before I can take a proper look but I am excited about consolidating everything on one really nice Intel driver.

**Comment by mwiget** [comment]
Indeed excellent work! Hope to take it for a spin some time for lw4o6.

**Comment by teknico** [comment]
Not work-in-progress anymore (we'll update title and description soon), so feel free to look at these changes in detail.

We already have [another branch](https://github.com/Igalia/snabb/pull/841), based on this one, which switches the whole codebase to use the `intel_mp` driver, and will create a PR for it once we deal with any changes needed here.

**Comment by lukego** [comment]
Should we close this PR as superseded by #1199?

**Comment by takikawa** [comment]
Yes, this PR has been superseded by #1197 (#1199 builds on #1197 instead of this PR) which has a few more commits, so I'll go ahead and close this one. Thanks for the reminder.

**Pull request closed without merging**
