### PR TITLE
intel_mp: move shm initialization to constructor

### PR DESCRIPTION
**Pull request by alexandergall**
Initialisation of the shm frame needs to be done in the constructor
method to avoid being overwritten by the frame created in core.app.

Add a copy of the mtu to the device-specific stats table, add a
counter to record the speed of the interface.

### CODE REVIEW

**Comment by eugeneia** [comment]
> Initialisation of the shm frame needs to be done in the constructor
method to avoid being overwritten by the frame created in core.app.

Could you elaborate on that? I feel like I should understand this, but I don’t. `core.app` calls `shm.create_frame` only once after calling the `new` method of an app, so how does it get overwritten?

```
-bash-4.3$ ./snabb snsh -i
Snabb> Foo = { shm = "foo" }
Snabb> function Foo:new () return setmetatable({}, {__index=Foo}) end
Snabb> f = Foo:new()
Snabb> =Foo.shm
foo
Snabb> =f.shm
foo
Snabb> f.shm = "bar"
Snabb> =Foo.shm
foo
Snabb> =f.shm
bar
```

**Comment by alexandergall** [comment]
When the frame is created, the counters are set to their default values, hence the original
```
counter.set(self.shm.mtu, self.mtu)
```
in `new()` has no effect. The patch sets the default value instead.

**Comment by alexandergall** [comment]
Can we please proceed with this PR?

**Comment by alexandergall** [comment]
Thanks. So can someone please merge?

**Pull request merged**
