### PR TITLE
Use intel_mp driver instead of intel10g driver

### PR DESCRIPTION
**Pull request by wingo**
This PR flips the switch in `lib.hardware.pci.device_info` to prefer the intel_mp driver instead of intel10g.  It also ports over the `firehose` and `packetblaster` programs to intel_mp, also porting the `loadgen` app from intel10g.  All credit to @teknico and @takikawa for the great patches!

### CODE REVIEW

**Comment by wingo** [comment]
Rebased to fix a bug in packetblaster.

**Comment by wingo** [comment]
This build failure is only `ERROR snabbnfv-iperf-1500 -> 0.828682 of 5.16 (SD: 0.709084 )`.  If I interpret this correctly, that would indicate perf of 4.28, which is 0.884 off from the mean; a bit more than a standard deviation, again if I understand it correctly.  I looked to see and it seems we don't have any pending perf patches in `lwaftr`.  So, I will push this branch to `wingo/optimize` to see what Hydra thinks of its perf.

**Comment by lukego** [comment]
Thanks @wingo.

@eugeneia Perhaps we should disable the performance tests on SnabbBot since they are mostly firing on false positives? Hydra will always catch regressions a step or two before they merge to master so we have a safety net.

**Comment by wingo** [comment]
FWIW @lukego I still get some value from these tests.  In particular the snabbnfv-loadgen-dpdk test on #1231 let me know that the `bench` mode of `snabbnfv` was broken with that branch, so I landed a fix.  In this case the benchmark could be an early warning perf error, but it's more of an indicator that I need to look more into Hydra results, whereas sometimes I don't bother.  So I appreciate them being there.

Whether the snabb-bot benchmarks should gate merges or not is another question :)

**Comment by lukego** [comment]
Okidok. I am fine with any alternative including leaving things as they are.

**Pull request merged**
