### PR TITLE
Upstreaming Snabbwall app

### PR DESCRIPTION
**Pull request by takikawa**
This is a PR for upstreaming Snabbwall for review by @kbara for `kbara-next` (the PR targets `next` for CI purposes). The downstream branch now lives at `Igalia/snabb` (now a protected branch too) and I've added a commit that updates `doc/branches.md` as well.

### CODE REVIEW

**Comment by takikawa** [comment]
Note: I updated snabbwall by merging in `next` (usually snabbwall has tracked only released versions) to avoid the merge conflict in this PR (so, e.g., CI can run).

**Comment by kbara** [comment]
Thank you. @aperezdc has agreed to change the ljndpi license to Apache 2.0 from MIT as well.

If anyone in the Snabb community has any reservations about Snabb containing a wrapper for an LGPLv3 library (ndpi), please speak up quickly. :-)

**Comment by aperezdc** [comment]
I have just pushed [version 0.1.0 of ljndpi](https://github.com/aperezdc/ljndpi/releases/tag/v0.1.0). Despite the version bump, the functionality is the same as the previous (`v0.0.3`), with the license now being Apache 2.0. It should be reasonably easy to pull the changes into your local branch and update the PR.

**Comment by takikawa** [comment]
@aperezdc thanks, the branch should be updated with your license change now.

**Comment by eugeneia** [comment]
@takikawa the [selftest fails](https://gist.github.com/SnabbBot/00421fd52b760de25e643c9571293e70#file-log-L3838) on SnabbBot, presumably due to missing dependencies. Is there a list of those somewhere so I can add them to [snabb_bot.nix](https://github.com/snabblab/snabblab-nixos/blob/master/modules/snabb_bot.nix#L76)?

**Pull request merged**
