### PR TITLE
fix a bug in tcp fields

### PR DESCRIPTION
**Pull request by xnhp0320**
tcp.ack is the bit set in tcp flags
while tcp.ack_num should be the ack seq number.

### CODE REVIEW

**Comment by eugeneia** [comment]
Hi @xnhp0320 :-)

88da49f and ae53f4a look good to me, but the other commits seem out of scope of this PR (especially 3c77fb2 is suspicious, is this for a kernel without hugetlbfs support?) I will cherry pick those two commits if that’s ok?

**Comment by xnhp0320** [comment]
Oh, sorry!

The other patches are used to make snabb run on our own servers, which seems have a 
old version of libc that does not support HUGETLB flags. 

You can just use the two patches. 

Sorry for the late response.

**Comment by eugeneia** [comment]
No problem at all. Merged, thank you!

**Comment by eugeneia** [comment]
Closing because the requested changes landed in v2018.06

**Pull request closed without merging**
