### PR TITLE
Macaddr is not a valid parameter when Intel82599 is SingleFunction

### PR DESCRIPTION
**Pull request by dpino**
MAC address cannot be set if Intel82599 NIC is instantiated as a SingleFunction (no VMDq mode). Method `new_sf(conf)` in `intel10g.app` does not expect a `macaddr` parameter.

On the other hand, there isn't either methods in `M_sf` to set a MAC address AFAIK (the NIC runs in promiscuous mode set at `M_sf:init_receive()`).

### CODE REVIEW

**Comment by wingo** [comment]
Related to #749.

For me I am OK merging this as it fixes a bug, but ideally I'd prefer a patch that *adds* support for mac address filtering to the SF interface.  LMK, otherwise I merge this later.

**Comment by dpino** [comment]
@wingo OK, let me try to hack a patch that enables mac address filtering in SF.

**Comment by dpino** [comment]
@wingo The additional patches add support for `promisc` parameter in SF which activates or deactivates promiscuous mode.  When promiscuous mode is off, the NIC filters Rx packets by MAC destination address. That's reflected by printing out the the RXNFGPC (Non-Filtered Good Rx Packets Counter) and RXDGPC (DMA Good Rx Packet Counter). When promiscuous mode is off RXDGPC is zero.

The point is that to properly test non promiscuous mode, it's necessary to craft packets with MAC addresses of the tested NICs.

Another possibility could be to add a method `set_mac` which overrides the actual MAC of the NIC. I think there's a way to restore the MAC from the firmware. Let me know if this more what you had a in mind.

**Comment by wingo** [comment]
Looking good.  Would you mind changing "promisc" to "promiscuous" throughout, and changing set_promiscuous_mode to take a boolean argument instead of having the separate unset function, please.  Thanks :)

**Comment by lukego** [comment]
Background question: Is there an application where it is important to disable promiscuous mode on a single-function NIC?

**Comment by mwiget** [comment]
Is there an API to retrieve the hardware mac of the intel nic via the intel10g app? I couldn't find one. Particularly in single-function app, its desirable to actually use the hardware mac instead of making up one. I know the workaround of loading the ixgbe driver and retrieve the mac via ethtool/ifconfig or read from the filesystem directly, but wonder why there isn't a Snabb function to do so directly.

@lukego : on single-function NIC and disabling promiscuous mode, yes, I do see a use case. It has to do with VLAN filtering. If Snabb is connected to an Ethernet switch port, that port might offer additional VLANs, resulting in Snabb requiring to handle (throw away)  untagged, single or double tagged packets. VMDq helps here.

**Comment by lukego** [comment]
The reason we lack a function for MAC address lookup is historical: we have used VMDq with MAC addresses assigned by QEMU and haven't had a use for the one programmed in EEPROM.

My mind is on the "straight NIC" concept (#801) at the moment so I am viewing every new feature on the `intel10g` driver as a step forward on the one hand (more functionality available) and a step back on the other (further from feature parity between drivers). Still: that is a background consideration since the whole do-it-all-in-software concept is not proven yet.

**Comment by alexandergall** [comment]
A bit late to the party :) @mwiget I've added that code a long time ago: https://github.com/snabbco/snabb/blob/master/src/apps/intel/intel10g.lua#L202

**Comment by mwiget** [comment]
@alexandergall: cool and very useful, thanks!

**Comment by dpino** [comment]
Closing this PR as macaddress is now used in SF mode (commit: 28a3de15)

**Pull request closed without merging**
