### PR TITLE
Update pflua

### PR DESCRIPTION
**Pull request by kbara**
Upstreaming of #1088 , Asumu's recent improvements to pflua.

### CODE REVIEW

**Comment by lukego** [comment]
@kbara I should have merged this already. Sorry about that. Is it okay to take this immediately after the imminent release?

**Comment by kbara** [comment]
No worries. I think that's ok. I'm tagging @takikawa so that he knows as well.

**Comment by takikawa** [comment]
Yes, thanks that's fine with me too. (and having this merged right after the next release will be helpful for the upcoming Snabbwall PR, which depends on a few changes in this PR)

**Comment by kbara** [comment]
Thank you.

**Pull request merged**
