### PR TITLE
Upstream lwaftr and snabbvmx work from last 6 months

### PR DESCRIPTION
**Pull request by wingo**
Now that #1047 is reviewed I landed it into `wingo-next`.  This PR is to merge `wingo-next` to `next`.  Assigning to @lukego :)

### CODE REVIEW

**Comment by wingo** [comment]
Hydra report here: https://hydra.snabb.co/build/739387
Relevant diff will be between `next` and `wingo-optimize`, though the comparison to `master` is interesting as well.

**Comment by wingo** [comment]
Hydra's done, I see no significant difference between next and wingo-optimize.  Let's ride this train to next!

**Comment by lukego** [comment]
Groovy. Code looks good. (Github UI is not much help with a 10KLOC diff but Emacs [magit-mode](https://magit.vc/screenshots/) is awesome: makes it really easy to jump back and forth between the "diffstat" list of filenames with +/- lines and the actual changes.)

Just waiting for my usual Hydra jobs (`lukego/next-tributary` and `lukego/next-tributary-murren`, evaluations [4108](https://hydra.snabb.co/eval/4108) and [4017](https://hydra.snabb.co/eval/4108)) to confirm. Shouldn't be long.

**Comment by wingo** [comment]
AFAIU the hydra jobs don't show a significant change relative to next.  WDYT @lukego ? :)

**Comment by lukego** [comment]
Merged, thanks!

**Pull request merged**
