### PR TITLE
App-local statistics counters

### PR DESCRIPTION
**Pull request by eugeneia**
This branch implements per-app statistics counters and uses this feature to implement statistics for Intel_app (per pciaddress actually) and vhost_user.

The basic mechanism is that each app now has a `shmpath` (automatically set based on its name) to which `core.shm.path` is set to when its methods are executed. `core.counter` is updated to use `core.shm.resolve`, so counters opened in `app:new` are created under the app's `shmpath`. Another convention in this PR is that apps store their counters in their `counters` field.

[doc/statistics.md](https://github.com/eugeneia/snabb/blob/statistics-superset/src/doc/statistics.md#statistics-counters-in-snabb) describes the schema used for the counters defined by this PR. It deviates from related standards in the way it counts packets. E.g. it defines  broadcast packet counts ⊆ multicast packet counts ⊆ total packet counts. I think this makes the most sense because it allows app authors to choose how fine grained their stats are. I also don't think we should buy into the [ifType](https://www.iana.org/assignments/ianaiftype-mib/ianaiftype-mib) madness.

The SNMP code formerly in `intel10g.lisp` was extracted to `lib.ipc.shmem.iftable_mib` using the schema / API described above.

Anything in this PR is open for discussion change (obviously), but I would like to get it merged and then develop these features incrementally to get things rolling. E.g. @alexandergall has pointed out that we need more data types than counters, etc. My rationale is that with this PR merged we can start recording important statistics in other apps.

App counters (as well as link counters) can be read using `snabb top -c`, e.g.:

```
bash-4.3# program/snabbnfv/selftest.sh > nfv.log &
bash-4.3# ./snabb top -c A_Virtio
 dtime                          1,465,310,436                 
 rxbytes                        18,186,581,184                
 rxdrop                         0                             
 rxmcast                        9                             
 rxpackets                      12,012,296                    
 txbytes                        85,150,962                    
 txmcast                        0                             
 txpackets                      990,127                       
 type                           4,097                         
bash-4.3# ./snabb top -c 'A_NIC.tx -> A_Virtio.rx'
 dtime                          1,465,310,436                 
 rxbytes                        174,939,590                   
 rxpackets                      2,032,431                     
 txbytes                        174,939,590                   
 txdrop                         0                             
 txpackets                      2,032,431                     
bash-4.3# ./snabb top -c 0000:01:00.0
 dtime                          1,465,310,436                 
 macaddr                        0                             
 mtu                            9,014                         
 promisc                        1                             
 rxbcast                        0                             
 rxbytes                        0                             
 rxdrop                         0                             
 rxerrors                       0                             
 rxmcast                        0                             
 rxpackets                      0                             
 speed                          10,000,000                    
 status                         1                             
 txbcast                        0                             
 txbytes                        1,518                         
 txdrop                         0                             
 txerrors                       0                             
 txmcast                        17                            
 txpackets                      17                            
 type                           4,096                         
```

### CODE REVIEW

**Comment by kbara** [comment]
Nice work! I've merged it onto kbara-next.

**Comment by kbara** [comment]
@eugeneia Shall I merge your newest change onto kbara-next as well?

**Comment by alexandergall** [comment]
Can you guys please also consider https://github.com/eugeneia/snabb/pull/14? Sorry, I'm losing track of who merges what from whom :)

**Comment by eugeneia** [comment]
@kbara No need to merge new commits from this branch, they are related to the performance regression in `next`.

@alexandergall Generally everything happens on the snabbco repository, e.g. opening PRs on my fork will be invisible to everyone but me. Best to close/reopen your PR on the source repository, then it will be picked up by the regular maintenance flow.

**Pull request merged**
