### PR TITLE
next: Changes queue for v2018.06

### PR DESCRIPTION
**Pull request by lukego**
This pulls the changes aggregated on `max-next` (#1350) and `wingo-next` (#1349) and should be good to go!

I reckon we can pull RaptorJIT onto `next` immediately after this release. It's working well for a bunch of people now (as discussed on Slack) but I don't think we need to squeeze it into this release. Seems worth a little extra time to e.g. review whether the README/documentation needs to be updated etc.

(Sorry for the relatively few cycles spent on upstreamery lately... It's a busy summer for me...)

### CODE REVIEW

**Comment by eugeneia** [comment]
@lukego This is good to go except my `lib.numa` fixes (#1269) are broken, so we should revert 
3120d7c.

**Comment by lukego** [comment]
@eugeneia Revert pushed! Sorry about the wait.

**Comment by eugeneia** [comment]
@lukego I am afraid I found another regression: I have bisected a SnabbNFV selftest failure down to https://github.com/snabbco/snabb/pull/1361/commits/d4c2eca9fbee860a438217832e6661f789aad524 (the merge commit, not thecommit to be merged.) So https://github.com/snabbco/snabb/pull/1361/commits/d4c2eca9fbee860a438217832e6661f789aad524 should be reverted from the release so I can figure out what is wrong with it.

**Comment by eugeneia** [comment]
Actually, never mind my last comment. The test was non-deterministic during bisect so the result is likely bogus.

**Pull request merged**
