### PR TITLE
[wip] rewrite pci.c in lua, support both flocked and unflocked memory maps

### PR DESCRIPTION
**Pull request by petebristow**
The main motivation of this is to support multiple processes attaching to the same NIC, to support features such as RSS. 
What's the best approach to breaking API changes like this?
Does anyone know why `assert(S.open())` works in `ljsyscall/test/test.lua` but requires a `tostring()` in snabb ?

### CODE REVIEW

**Comment by lukego** [comment]
Woohoo! Goodbye more C glue code :-)

I think the basic protocol for changing the API like this is to update the documentation and any callers that we have in the repo. I like this [monorepo](http://danluu.com/monorepo/) concept description that @kbara linked to!

Maybe @kbara or @wingo would like to be upstream for this one?

**Comment by kbara** [comment]
I'm happy to merge this as-is; really nice work. I'll wait until tomorrow to merge it in case @lukego or @eugeneia wants to chime in about the breaking API change or any other major details, if @petebristow makes a PR targeting kbara-next; otherwise, I can manually merge it, but I can't (and wouldn't) merge it directly to snabbco:master.

**Comment by eugeneia** [comment]
@kbara Please make sure SnabbBot passes this before merging.

**Comment by eugeneia** [comment]
> Does anyone know why assert(S.open()) works in ljsyscall/test/test.lua but requires a tostring() in snabb ?

@petebristow I believe ljsyscall redefines `assert` in that file to use `tostring`.

**Comment by kbara** [comment]
@eugeneia oops, indeed. Thanks.

**Comment by petebristow** [comment]
@eugeneia Thanks, I couldn't see it for looking.

**Comment by petebristow** [comment]
@kbara Please don't merge this for now.

**Pull request closed without merging**
