### PR TITLE
[wip] Ipv6 tunnel diagnostics

### PR DESCRIPTION
**Pull request by lukego**
Add counters to the `keyed_ipv6_tunnel` app:
- `drop_bad_cookie`
- `drop_bad_length`
- `drop_bad_local_address`
- `drop_bad_protocol`
- `drop_bad_remote_address`

This is to make the reasons for packet drops more transparent.

### CODE REVIEW

**Comment by lukego** [comment]
Depends on (includes commits from) #766 to make the engine create the counters locally for each app instance.

**Comment by eugeneia** [comment]
This is super cool obviously. I propose a counterpart to this in `snabbtop`, it should be able to list the counters of a selected app. E.g. so we can do this from a shell:

```
$ snabbtop tunnelXY
drop_bad_cookie         10
drop_bad_length          0
drop_bad_local_address   7
drop_bad_protocol       29
drop_bad_remote_address  3
```

Should be straight forward to implement and I would be willing to tackle this.

**Comment by lukego** [comment]
@eugeneia Cool idea :)

**Comment by lukego** [comment]
Great catch, SnabbBot! Have to think about correctly managing the lifetime of those counter objects to avoid errors and/or memory mapping leaks when recreating app instances.

**Comment by lukego** [comment]
(Added `[wip]` because of bug that needs to be fixed. Possibly overkill since SnabbBot has already marked this change as failing tests.)

**Comment by lukego** [comment]
Thinking about how to manage the lifecycle of counter objects. How about if we leave that to the engine?

For example we could define a new app callback:

```
function myapp:counters ()
   return {'drop_bad_checksum', 'drop_bad_cookie', ...} 
end
```

and then the engine could create these on app init (and delete them on app stop) and make them accessible via:

```
counter.add(self.counter.drop_bad_checksum, 1)
```

Reasonable? I am not sure what a cleaner alternative would be that is not error-prone.

**Comment by eugeneia** [comment]
I would probably use a slot similar to `zone` that can optionally be populated in `new` instead of a dedicated method. E.g.

```
function MyApp:new (arg)
  ...
  local o = {}
  o.counters = {'drop_bad_checksum', 'drop_bad_cookie', ...}
  ...
end
```

Any reason why you chose a method?

**Pull request closed without merging**
