### PR TITLE
nDPI2.x snabb compatibility

### PR DESCRIPTION
**Pull request by aouinizied**
In this PR, nDPI 2.x versions are correctly handled.
Modifications summary:
* lib/ljndpi/ndpi/c.lua: fix versions checks (major and minor values)
* generate protocol_ids_2_x.lua (till the most recent version 2.3)

### CODE REVIEW

**Comment by aouinizied** [comment]
@dpino @lukego 
Note that ntop team starts to implement (experimental) hyperscan based algorithm. If you have hyperscan lib on your machine, nDPI compilation process will take this headers and compile with hyperscan enabled. Such new headers and functions are not handled with current ljndpi bindings. 
I will take a look at it when I have free slots. At least, we have a trace here.

Best regards,
Zied

**Comment by aouinizied** [comment]
UP. as it was merged on September release. Do you need any further checks?

Zied

**Comment by eugeneia** [comment]
@takikawa @dpino Unless you have any objections I would merge this onto max-next.

**Comment by dpino** [comment]
@eugeneia sgtm

**Pull request merged**
