### PR TITLE
Merge max-next into next (v2018.01-2)

### PR DESCRIPTION
**Pull request by eugeneia**
Includes #1262 (tested with #1220) plus some fixes to tests:

 * `lib.lpm.*` selftests are less excessive by default (intensive tests are put behind a environment variable) Cc @petebristow 
* ~~`lib.numa` selftest is skipped when run on a non-NUMA system~~

### CODE REVIEW

**Comment by wingo** [comment]
The lib.numa selftest should also work on non-NUMA systems.  It works for me.  What's the deal?  I would appreciate to be asked to review lib.numa changes.

**Comment by wingo** [comment]
I think this PR would be better if the LPM test disabling and the lib.numa changes first had their own PRs before reaching max-next.  I had the impression that max-next is a merge branch and not a development branch; is that correct?

**Comment by eugeneia** [comment]
@wingo Right, I was under the impression that the changes in https://github.com/snabbco/snabb/pull/1267/commits/a0c9d21c8f5b2bc7acae0fe1fc74f375ad20da24 (Merge branch 'economic-selftests' into max-next) were too trivial to warrant their own PR. Probably the wrong decision in retrospect.

On v2017.12 and `next` (without 2c71c23) I get an error[1] when running the `lib.numa` seltest. Maybe 2c71c23 is the wrong solution, if you agree I can revert that commit.

[1]:
```
→ sudo ./snabb snsh -t lib.numa
selftest: numa
core/main.lua:26: Function not implemented

Stack Traceback
===============
(1) Lua function 'handler' at file 'core/main.lua:168' (best guess)
	Local variables:
	 reason = string: "core/main.lua:26: Function not implemented"
	 (*temporary) = C function: print
(2) global C function 'error'
(3) Lua global 'assert' at file 'core/main.lua:26'
	Local variables:
	 v = nil
(4) Lua global 'bind_to_numa_node' at file 'lib/numa.lua:116'
	Local variables:
	 node = number: 0
(5) Lua global 'bind_to_cpu' at file 'lib/numa.lua:103'
	Local variables:
	 cpu = number: 0
	 cpu_and_node = table: 0x419eb8c8  {cpu:0, node:0}
(6) Lua global 'test_cpu' at file 'lib/numa.lua:134'
	Local variables:
	 cpu = number: 0
	 node = nil
(7) Lua field 'selftest' at file 'lib/numa.lua:152'
	Local variables:
	 (for index) = number: 0
	 (for limit) = number: 1023
	 (for step) = number: 1
	 cpuid = number: 0
(8) Lua function 'opt' at file 'program/snsh/snsh.lua:31' (best guess)
	Local variables:
	 arg = string: "lib.numa"
(9) Lua field 'dogetopt' at file 'core/lib.lua:425'
	Local variables:
	 args = table: 0x4062b8d8  {1:-t, 2:lib.numa}
	 actions = table: 0x40754520  {t:function: 0x40e89798, q:function: 0x40754568, P:function: 0x40626f78 (more...)}
	 opts = string: "hl:p:t:die:j:P:q:"
	 long_opts = table: 0x40628810  {jit:j, help:h, program:p, test:t, load:l, package-path:P, debug:d, sigquit:q (more...)}
	 opts = table: 0x419e9460  {1:t}
	 optind = number: 3
	 optarg = table: 0x406288d8  {1:lib.numa}
	 (for generator) = C function: builtin#6
	 (for state) = table: 0x419e9460  {1:t}
	 (for control) = number: 1
	 i = number: 1
	 v = string: "t"
(10) Lua field 'run' at file 'program/snsh/snsh.lua:65'
	Local variables:
	 parameters = table: 0x4062b8d8  {1:-t, 2:lib.numa}
	 profiling = boolean: false
	 traceprofiling = boolean: false
	 start_repl = boolean: false
	 noop = boolean: true
	 program = nil
	 opt = table: 0x40754520  {t:function: 0x40e89798, q:function: 0x40754568, P:function: 0x40626f78 (more...)}
(11) Lua function 'main' at file 'core/main.lua:67' (best guess)
	Local variables:
	 program = string: "snsh"
	 args = table: 0x4062b8d8  {1:-t, 2:lib.numa}
(12) global C function 'xpcall'
(13) main chunk of file 'core/main.lua' at line 230
(14)  C function 'require'
(15) global C function 'pcall'
(16) main chunk of file 'core/startup.lua' at line 3
(17) global C function 'require'
(18) main chunk of [string "require "core.startup""] at line 1
	nil
```

**Comment by wingo** [comment]
@eugeneia I've never seen that error before; weird.  Yes please revert, the proper thing to do is to fix the bug.  Can you open an issue for that please?  I believe the error corresponds to an "ENOSYS" from ljsyscall, probably on the "S.get_mempolicy" syscall.  What kernel version are you running?  Did you specialize the kernel configuration perhaps?

**Pull request merged**
