### PR TITLE
Merge wingo-next (#1032, #919)

### PR DESCRIPTION
**Pull request by wingo**
A small PR to prime the `wingo-next` pump :)

### CODE REVIEW

**Comment by wingo** [comment]
FYI I will push additional merges on this PR until someone assigns themselves to give it the :+1: or :no_good_man: :)

**Comment by kbara** [comment]
The general person to do that is @lukego . 

The usual process these days:
a) Someone submits a PR
b) One of the three upstreams (hi fellow upstream!) assigns that to themselves
c) The upstream merges the patch(es) into theirname-next, and Luke takes it from there

**Comment by wingo** [comment]
@kbara this branch is already past a, b, and, c, and is now for luke or whoever merges to master.  i just wanted to put the heads up that this branch could get more patches until someone (luke i guess) assigns themself to indicate start-of-review.

**Comment by kbara** [comment]
Yep, was just wanting to say "in practice, that always seems to be Luke, by policy" :)

**Comment by lukego** [comment]
@wingo Groovy. I am waiting for the [next-tributary](https://hydra.snabb.co/eval/4010) and [next-tributary-murren](https://hydra.snabb.co/eval/4009) tests to complete and then I will check it out.

Suits me fine if you want to push more updates. I'll assume that I am welcome to merge the branch while the PR is open (unless marked [wip] etc) unless told otherwise.

I think we are all already on the same page about this, but just in the interest of over-communicating, I generally rely on the code coming from `-next` branches to already be reviewed and for me to mostly be playing integrator e.g. checking the CI results for potential release-blockers and so on.

**Comment by lukego** [comment]
Merged, thanks! Code and tests look good.

**Pull request merged**
