### PR TITLE
Add pcap packet tap

### PR DESCRIPTION
**Pull request by wingo**
See README for details.

### CODE REVIEW

**Comment by eugeneia** [comment]
Is this supposed to remove the docs for `apps.pcap.pcap`?

**Comment by wingo** [comment]
Aah, the docs removal is an error!  Will fix.

**Comment by wingo** [comment]
Ping @eugeneia :-)

**Comment by eugeneia** [comment]
LGTM

note to self: sort out these weird false positive merge conflicts in SnabbBot,

**Pull request merged**
