### PR TITLE
LPM library for IPv4 addresses

### PR DESCRIPTION
**Pull request by petebristow**
@plajjan something for you to look at if nothing else ;)

### CODE REVIEW

**Comment by lukego** [comment]
This looks quite exciting :)

**Comment by plajjan** [comment]
It appears to be some performance tests in the code that do some profiling. Are those tests run in CI? Can I see the output somewhere?

**Comment by petebristow** [comment]
@plajjan They are run as part of the CI, it doesn't pin the test to a single core though so `lib.pmu` complains. @eugeneia @lukego Is that a problem with my tests or a CI problem ?

The results below are run on a 2.30GHz Sandybridge. 
The routes are randomly generated, this makes DXR slow, it's much faster with the DFZ.
LPM4_trie is very slow, it's more a RIB thing.

LPM4_248 with 15bit values
EVENT                                             TOTAL     /lookup
cycles                                    1,802,696,930      18.027
ref_cycles                                            0       0.000
instructions                              2,002,673,892      20.027
mem_load_uops_retired.l2_hit                      2,806       0.000
mem_load_uops_retired.l2_miss                       525       0.000
mem_load_uops_retired.llc_hit                       416       0.000
mem_load_uops_retired.llc_miss                      103       0.000
lookup                                      100,000,000       1.000

data dependency
EVENT                                             TOTAL     /lookup
cycles                                    6,041,667,188      60.417
ref_cycles                                            0       0.000
instructions                              3,609,026,013      36.090
mem_load_uops_retired.l2_hit                    654,274       0.007
mem_load_uops_retired.l2_miss                99,145,450       0.991
mem_load_uops_retired.llc_hit                99,110,090       0.991
mem_load_uops_retired.llc_miss                   35,288       0.000
lookup                                      100,000,000       1.000

no dependency
EVENT                                             TOTAL     /lookup
cycles                                    3,877,605,508      38.776
ref_cycles                                            0       0.000
instructions                              3,105,981,080      31.060
mem_load_uops_retired.l2_hit                    683,391       0.007
mem_load_uops_retired.l2_miss                98,879,708       0.989
mem_load_uops_retired.llc_hit                75,359,843       0.754
mem_load_uops_retired.llc_miss               23,519,812       0.235
lookup                                      100,000,000       1.000


LPM4_248 with 31bit values
EVENT                                             TOTAL     /lookup
cycles                                    1,802,816,314      18.028
ref_cycles                                            0       0.000
instructions                              2,002,669,707      20.027
mem_load_uops_retired.l2_hit                      2,742       0.000
mem_load_uops_retired.l2_miss                       660       0.000
mem_load_uops_retired.llc_hit                       397       0.000
mem_load_uops_retired.llc_miss                      241       0.000
lookup                                      100,000,000       1.000

data dependency
EVENT                                             TOTAL     /lookup
cycles                                    6,038,493,398      60.385
ref_cycles                                            0       0.000
instructions                              3,509,189,183      35.092
mem_load_uops_retired.l2_hit                    329,337       0.003
mem_load_uops_retired.l2_miss                99,480,639       0.995
mem_load_uops_retired.llc_hit                99,441,646       0.994
mem_load_uops_retired.llc_miss                   38,855       0.000
lookup                                      100,000,000       1.000

no dependency
EVENT                                             TOTAL     /lookup
cycles                                    5,052,005,406      50.520
ref_cycles                                            0       0.000
instructions                              3,107,544,344      31.075
mem_load_uops_retired.l2_hit                    344,854       0.003
mem_load_uops_retired.l2_miss                99,245,765       0.992
mem_load_uops_retired.llc_hit                37,834,608       0.378
mem_load_uops_retired.llc_miss               61,411,092       0.614
lookup                                      100,000,000       1.000

LPM4_dxr
EVENT                                             TOTAL     /lookup
cycles                                    1,802,773,939      18.028
ref_cycles                                            0       0.000
instructions                              2,002,707,041      20.027
mem_load_uops_retired.l2_hit                      2,589       0.000
mem_load_uops_retired.l2_miss                       575       0.000
mem_load_uops_retired.llc_hit                       448       0.000
mem_load_uops_retired.llc_miss                      120       0.000
lookup                                      100,000,000       1.000

data dependency
EVENT                                             TOTAL     /lookup
cycles                                   17,693,204,598     176.932
ref_cycles                                            0       0.000
instructions                             11,262,319,609     112.623
mem_load_uops_retired.l2_hit                 31,486,717       0.315
mem_load_uops_retired.l2_miss               357,800,594       3.578
mem_load_uops_retired.llc_hit               357,798,489       3.578
mem_load_uops_retired.llc_miss                    1,820       0.000
lookup                                      100,000,000       1.000

no dependency
EVENT                                             TOTAL     /lookup
cycles                                   14,990,055,096     149.901
ref_cycles                                            0       0.000
instructions                             10,783,918,937     107.839
mem_load_uops_retired.l2_hit                 29,846,837       0.298
mem_load_uops_retired.l2_miss               340,099,663       3.401
mem_load_uops_retired.llc_hit               340,098,552       3.401
mem_load_uops_retired.llc_miss                      841       0.000
lookup                                      100,000,000       1.000

LPM4_trie
EVENT                                             TOTAL     /lookup
cycles                                       18,104,359      18.104
ref_cycles                                            0       0.000
instructions                                 20,063,983      20.064
mem_load_uops_retired.l2_hit                        167       0.000
mem_load_uops_retired.l2_miss                       222       0.000
mem_load_uops_retired.llc_hit                       221       0.000
mem_load_uops_retired.llc_miss                        1       0.000
lookup                                        1,000,000       1.000

data dependency
EVENT                                             TOTAL     /lookup
cycles                                    1,186,457,814    1186.458
ref_cycles                                            0       0.000
instructions                              1,502,740,505    1502.741
mem_load_uops_retired.l2_hit                  4,868,971       4.869
mem_load_uops_retired.l2_miss                 9,343,821       9.344
mem_load_uops_retired.llc_hit                 9,333,537       9.334
mem_load_uops_retired.llc_miss                   10,257       0.010
lookup                                        1,000,000       1.000

no dependency
EVENT                                             TOTAL     /lookup
cycles                                    1,187,639,448    1187.639
ref_cycles                                            0       0.000
instructions                              1,497,713,970    1497.714
mem_load_uops_retired.l2_hit                  4,863,939       4.864
mem_load_uops_retired.l2_miss                 9,348,050       9.348
mem_load_uops_retired.llc_hit                 9,293,004       9.293
mem_load_uops_retired.llc_miss                   55,023       0.055
lookup                                        1,000,000       1.000

**Comment by lukego** [comment]
> They are run as part of the CI, it doesn't pin the test to a single core though so lib.pmu complains. @eugeneia @lukego Is that a problem with my tests or a CI problem ?

Good question. Someone, somehow needs to arrange for this test to run with CPU affinity. Here is one idea: How about if the test cause would automatically take affinity to the core it is already running on?

```lua
local S = require("syscall")
local numa = require("lib.numa")
local current_cpu = S.getcpu().cpu
numa.bind_to_cpu(current_cpu)
```

This should be safe and "polite" since you are only locking affinity to a core that has already been assigned to you.

Could also implement this logic as a library routine in `lib.numa` and/or `snsh -t` if that made more sense to people.

**Comment by lukego** [comment]
@petebristow I'm looking into integrating the tests with CI. Good exercise to support running the perl code with suitable dependencies. I'm packaging `Net::Patricia` with nix over at https://github.com/NixOS/nixpkgs/pull/25908.

**Comment by lukego** [comment]
@petebristow Suit you if I merge this onto `next` now? I plan to separately take another look at the general problem of providing test suites with their required software dependencies.

**Comment by lukego** [comment]
Merged via #1203. Sorry about the wait!

**Comment by eugeneia** [comment]
@petebristow I tested this a bit (came in handy just at the right time, thanks!) and I am experiencing segmentation faults due to some memory corruption inside `lpm4_dxr.lua`.

**Pull request merged**
