### PR TITLE
Introduction of named programs

### PR DESCRIPTION
**Pull request by xray7224**
Hello,

This PR introduces named programs, as per the issue #1033. I plan to merge this via igalia/snabb but posting PR as I'd love more feedback from snabb devs.

Thanks!

### CODE REVIEW

**Comment by lukego** [comment]
Just a note that I have checked for a potential conflict with "process groups" over on #1021 and I do not think there will be a problem.

The idea of "process groups" is that Snabb processes will form a tree with parent/child relationships. The implementation does not change directory layout of `/var/run/snabb` and should be compatible. Every process (parents, children, grandchildren, etc) has its pid listed in `/var/run/snabb` and so any process should be able to call `claim_name()`.

I suppose that as application developers we would need to decide which processes should be named e.g. only the parent or also the children. Seems like we can decide this later.

I would welcome feedback on the process groups idea btw. Could be that it is ill-conceived or ill-described?

**Comment by eugeneia** [comment]
@xray7224 I am curious, is there a specific reason why you did not reorganize the `<pid>` directories into `by-pid/` after all?

**Comment by xray7224** [comment]
@eugeneia I decided it was probably fine as is. One of the main reasons for deciding this would be having to change `SNABB_SHM_ROOT` which is user configurable to not be the directory with the PID files in. Currently my code uses that as a base and creates "by-name" inside of it however, changing it to be `by-pid` leaves me with two choices:

1. Change what the `shm.root` (`SNABB_SHM_ROOT`) actually points to (a directory with both `by-pid` and `by-name`).

2. Use it as is but step back one directory from the root which seems like encroaching outside of the space set aside by the user.

If i were to do this I think I'd definitely go for option one and perhaps this change should be made WDYT?

**Comment by lukego** [comment]
Does this PR make `snabb top` work with process names? That would seem like a really nice feature. I am not using `snabb top` myself and the reason is perceived difficulty of identifying the right process (solved very neatly with names).

**Comment by wingo** [comment]
Probably we should put off making a change to the PID structure of /run/snabb until some time later -- people have different versions of tools and I think this PR lets old "snabb top" keep on working for a while.

**Comment by eugeneia** [comment]
@wingo I don’t think we can or should support a use case where an out-of-tree snabb top is used.

@xray7224 I don’t know what could possibly break so its easy for me to advocate a clean directory structure, but from my experience these hacks will just bite us later. I also think option 1 is reasonable.

Also :+1: to what @lukego said. This is a long standing issue, and I am not innocent in this regard. :-)

**Comment by wingo** [comment]
@eugeneia the use case wasn't external `snabb top`, it was rather a `snabb top` from some previous version or some other mainline-headed but potentially precisely mainline branch

**Comment by eugeneia** [comment]
@wingo That’s what I was referring to, too. Since top is built into the snabb executable, a matching version should always be available and used I think.

**Comment by lukego** [comment]
I am also concerned about the potential for mismatched Snabb versions to communicate via private interfaces that are incompatible. There could be many Snabb executables installed on a machine, $PATH could be different when a process is spawned via systemd vs managed via shell, software can be upgraded on disk while the previous version is still executing, etc. So I worry about this happening accidentally even if the policy would be that you should always use the same version.

I am not sure of an ideal solution. One possibility could actually be for processes like `snabb top` and `snabb config` to try and respawn themselves using the same executable as the target process. If there is a Snabb process running with pid 123 then the kernel will provide `/proc/123/exe` as a symlink to the executable that this process started from. I am using this over on #1021 to try and spawn worker processes using the same software as the parent. The weakness I see is that a symlink is based on name rather than inode and so it seems like you will still get a mismatch of the executable has been replaced on disk.

Could be possible to make a more fool-proof mechanism if the main Snabb process would immediately fork() a process that serves as a template for request processing i.e. could serve requests to fork new children...

**Comment by eugeneia** [comment]
@lukego In that case, how crazy would using a hard link be? I.e. `/var/run/snabb/123/snabb.exe`

**Comment by lukego** [comment]
@eugeneia Hard link to the executable would be nice but the implementation challenge is that unix hardlinks cannot span filesystems. So we cannot have a hardlink on the ramdisk (`/var/run`) pointing to the disk (e.g. `/usr`).

Could consider copying the whole executable instead? In the context of #1021 this could go into the `shm/group/` folder so we would only have one copy per process group. This would also make the `core.worker` process-spawning API robust to the snabb binary on disk being replaced while running.

**Comment by wingo** [comment]
Sorry I have to insist about the version thing.  There may be many versions of snabb on a system and you don't want "snabb top" to start doing weird things depending on which version/branch/etc of snabb top you run.  I do not want these bugs from my users!

**Comment by eugeneia** [comment]
@xray7224 Sorry for the long silence. I think this change should also update `snabb top` so that it can attach to named instances (see https://github.com/snabbco/snabb/pull/1058#issuecomment-258377887). I would like to merge it once that issue is addressed.

The remaining issues can be fixed later on:

- implement `snabb top` so that it always uses the snabb executable of the instance it attaches to
- possibly clean up directory structure

**Comment by eugeneia** [comment]
Ehh... I had forgotten that this is upstreamed via igalia/snabb, nevermind my last comment.

**Comment by eugeneia** [comment]
This did land upstream and can be closed, no? ❓ 🕵️‍

**Comment by xray7224** [comment]
Yeah it's landed upstream, thanks for the reminder. I'll close it.

**Pull request closed without merging**
