### PR TITLE
next: Changes queue for v2017.09 release

### PR DESCRIPTION
**Pull request by lukego**
Opening `next` for the new merge window...

### CODE REVIEW

**Comment by lukego** [comment]
So! I have been away on vacation and I am back now. Should we cut these changes immediately as the 2017.11 release and move on directly towards landing the new code on `wingo-next` and other PRs? what say you @eugeneia @wingo and all?

**Comment by eugeneia** [comment]
I am fine with either way! 👍

**Comment by wingo** [comment]
@lukego `wingo-next` contains pretty solid `intel_mp` changes from @takikawa and Nicola, only that there was one regression on i210 cards (iirc) that needs sorting out (`FAILED: ./test_1g_sw_sem.snabb`).  I would like to get that fixed and merged this week then I will get a lwaftr upstreaming sent upstream; we just finished a development cycle and so have a bunch of things to send.  If you need to make a Snabb release before merging `wingo-next` (#1231) that's fine too.

**Comment by lukego** [comment]
@eugeneia I suggest let's ship this branch now. That will reduce the backlog of changes and also get SnabbBot happy with master thanks to @wingo's fix to the lpm4 selftest case. Then we can focus on getting wingo-next merged and releasing that.

**Pull request merged**
